// THIS IS AUTOGENERATED FILE. DO NOT EDIT THIS FILE MANUALLY

import { DatabaseMigrationType } from './types'

import { InitDbMigration1692808917380 } from './migrations/1692808917380-init-db'
// INSERT_POSITION

export const migrationList: DatabaseMigrationType[] = [
  InitDbMigration1692808917380,
  // MIGRATION_LIST_POSITION
]
